---
- hosts: all
  become: true
  become_method: sudo
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install dependencies
      package:
        name:
          - bash-completion
          - docker
          - vim-enhanced
    - name: Add docker group
      group:
        name: docker
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: true
    - name: Start docker service
      service:
        name: docker
        enabled: true
        state: restarted
    - name: always load openvswitch module
      copy:
        dest: /etc/modules-load.d/openvswitch.conf
        content: openvswitch
    - name: load openvswitch module
      modprobe:
        name: openvswitch
